### ISSUE TITLE
progress bar when compressing

### ISSUE THREAD

**Issue by jtarchie** [SaveTheRbtz/zstd-seekable-format-go#121]
I am using the CLI to compress my files. With a rather large file, I was thinking a progress bar would be nice. Would you allow me to add one as a `--progress` flag?

**Comment by SaveTheRbtz** [comment]
Closed by:
* https://github.com/SaveTheRbtz/zstd-seekable-format-go/pull/143
* https://github.com/SaveTheRbtz/zstd-seekable-format-go/pull/123
