### ISSUE TITLE
getting size of compressed contents

### ISSUE THREAD

**Issue by jtarchie** [SaveTheRbtz/zstd-seekable-format-go#122]
It is my understanding that to get the size of the compressed contents, a `Seek(0, io.SeekEnd)` has to be performed. When this operation is performed, all the entries for the decompressed size appear to have to be sought.

I was trying to use a `ReaderAt` for HTTP Ranges, and when I did the `Seek`, the HTTP went denial-of-service because of how many HTTP requests it made.

I wondered if there was a way to implement a skippable frame that would include the overall decompressed size. This way, a single read could be made for the metadata.

**Comment by SaveTheRbtz** [comment]
The index that maps decompressed offsets to compressed ones is stored at the end of the file, so your HTTP-based implementation should be able to seek from the end of the file (bytes=-9).

The default environment[1] uses a couple of seeks calls to fetch the footer and the index from the end of the file.  You can potentially write your own environment for http backend that could store this footer in a separate files (that way you won't need to seek at all).  Or you can go even further and store each chunk in a separate file, that way, if your webserver does not support range-requests, it would still work.

PS. `Seek` method is purely in-memory[2], so it should not do any IO.

[1] https://github.com/SaveTheRbtz/zstd-seekable-format-go/blob/main/reader.go#L67-L80
[2] https://github.com/SaveTheRbtz/zstd-seekable-format-go/blob/4410daa6d511bbcef261f68a9f73e2d91b66375d/reader.go#L290-L310

**Comment by jtarchie** [comment]
Thanks for the lead. This is totally my bad. I'll take a look at what's causing this.
