### ISSUE TITLE
Support 386 arch

### ISSUE THREAD

**Issue by wolfogre** [SaveTheRbtz/zstd-seekable-format-go#146]
Hi maintainers! Thanks for this awesome package.

I'm working on introducing zstd seekable format to Gitea, see https://github.com/go-gitea/gitea/pull/31761.

Unfortunately, it doesn't support 386 arch.

<img width="1520" alt="image" src="https://github.com/user-attachments/assets/03203523-d111-41f8-94d1-62b8409d073b">

I checked the code, it seems that it's just some Golang syntax issues and shouldn't be difficult to fix.

I will try to send a PR to fix it, and I wonder if it's possible to release a new version when it has been fixed? I will be very grateful.

**Comment by SaveTheRbtz** [comment]
Thank you for the contribution, the release will be coming shortly

**Comment by wolfogre** [comment]
@SaveTheRbtz Thanks! However, I noticed that the new tag `v0.7.1` doesn't take effect on '/pkg' since there's a tag `pkg/v0.7.0`. Golang will use the last one when `go get github.com/SaveTheRbtz/zstd-seekable-format-go/pkg`.

**Comment by SaveTheRbtz** [comment]
@wolfogre the goal was to avoid leaking cmd's dependencies into the lib, e.g. progressbar, xterm, and cdc.

Going through [Go's module reference](https://go.dev/ref/mod#vcs-version), seems like tagging all new releases with pkg/v0.x.x should be enough to make it work:
```
$ go list -m -versions github.com/SaveTheRbtz/zstd-seekable-format-go/pkg        
github.com/SaveTheRbtz/zstd-seekable-format-go/pkg v0.7.0 v0.7.1 v0.7.2
```

Can you please re-verify if it works for your use-case?

**Comment by wolfogre** [comment]
@SaveTheRbtz 

> the goal was to avoid leaking cmd's dependencies into the lib, e.g. progressbar, xterm, and cdc.

I understand. But it's still unnecessary to split it into two modules, you can add a standalone go.mod for cmd. Like:
- go.mod
- cmd
  - abc
     - go.mod

Let me show you another example: [kratos](https://github.com/go-kratos/kratos)

You can find there are both `/go.mod` and `/cmd/kratos/go.mod`. `/cmd/kratos/go.mod` constains `github.com/fatih/color` while `/go.mod` doesn't. And kratos has clean tags.

I have ample experience with golang projects. If you are willing, I can provide more help regarding golang. You can find my emails address in my commit history. 😁

> Can you please re-verify if it works for your use-case

Thanks! It works now.

**Comment by SaveTheRbtz** [comment]
Thanks for good examples!  I come from a monorepo world where top-level module does not make much sense.  Let's keep package structure as is for now and see how it goes when more packages are added.  I wanted to eventually add an S3/GCP/Azure-based remote envs and maybe even content-addressable remote backend.

If it doesn't look good, we can always switch to a top-level package before the v1 release.

**Comment by wolfogre** [comment]
I completely understand. Anyway, thank you very much for this package!
